### ISSUE TITLE
Rename `dotdotdot` to `ellipsis`

### ISSUE THREAD

**Issue by neu5** [CezaryDanielNowak/React-dotdotdot#1]
Consider renaming this library to `ellipsis` while `dotdotdot` sounds extremely ridiculous

**Comment by CezaryDanielNowak** [comment]
http://poll.lab.io/ChG5uhmG6Zaywg1q1M2Kdg

**Comment by CezaryDanielNowak** [comment]
Still, you can rename it by:
`var Ellipsis = require('React-dotdotdot');`
or
`import Ellipsis from 'React-dotdotdot';`
or
`import {default as Ellipsis} from 'React-dotdotdot';`

**Comment by neu5** [comment]
I've won the poll: http://poll.lab.io/ChG5uhmG6Zaywg1q1M2Kdg/results
Deal with it 
![giphy](https://cloud.githubusercontent.com/assets/980955/12869769/0dca55fe-cd29-11e5-8b60-e137498f5425.gif)

**Comment by CezaryDanielNowak** [comment]
9:6 for dotdotdot.
![giphy](https://media.giphy.com/media/13py6c5BSnBkic/giphy.gif)
