### ISSUE TITLE
truncationHTML not working

### ISSUE THREAD

**Issue by ChocoMomo** [CezaryDanielNowak/React-dotdotdot#12]
The property truncationHTML isn't working.

**Comment by kkwiatkowski** [comment]
`truncationHTML` property is internal option of clamp and is not exposed as part of `react-dotdotdot` interface.

There is another property that is available, and you might be interested in it - `truncationChar`.

**Comment by ChocoMomo** [comment]
Well i need to truncate RichTexts with html tags in it and in the current situation i can't do that.

**Comment by maulikso** [comment]
It is not an internal option in Clamp.js I guess. https://github.com/josephschmitt/Clamp.js/#options

**Comment by CezaryDanielNowak** [comment]
This is fixed in 1.2.1. Regards
