### ISSUE TITLE
long unbroken words overflow without getting truncated

### ISSUE THREAD

**Issue by TomiHiltunen** [CezaryDanielNowak/React-dotdotdot#15]
Long words will not get truncated correctly:

<img width="315" alt="cursor_and_seriousfuckinglongnameforagoddamncommunityonasocialnetworkingsite_ _hubchat" src="https://cloud.githubusercontent.com/assets/2010468/23260107/fc0001f6-f9d8-11e6-902c-c0b94d0a1e75.png">

**Comment by CezaryDanielNowak** [comment]
You can try to fix it with CSS: https://developer.mozilla.org/en/docs/Web/CSS/hyphens

**Comment by dazorni** [comment]
We currently have the same problem: In the inspection this is fixed for chrome by removing the `display: -webkit-box` style. In Safari the current implementation works but it does also work without the `display` style. Is this display style really needed?

Current browser versions are: 
```
Chrome: 58.0.3029.110 (64-bit)
Safari: 10.1 (12603.1.30.0.34)
```

**Comment by CezaryDanielNowak** [comment]
Proper display property allows to calculate element's width/height. With different `display` for text container - lib might work incorrectly

**Comment by dazorni** [comment]
@CezaryDanielNowak In my current chrome version it doesn't work with the `display` property 😞  Is there anything we could do?

**Comment by dalkir** [comment]
@TomiHiltunen Try with css: `word-break: break-word;` it worked for me.

**Comment by alexandresebrao** [comment]
Why react-dotdotdot doesn't accept style as prop so this could be fixed internely when we use inline style

**Comment by CezaryDanielNowak** [comment]
Please retest with latest version

**Comment by fsmaia** [comment]
Just retested with latest version and problem still works. Long unbroken words lead to unexpected overflow.
