### ISSUE TITLE
Why return a div instead of a span? 

### ISSUE THREAD

**Issue by arovillard** [CezaryDanielNowak/React-dotdotdot#16]
otherwise I get errors like this `<div> cannot appear as a descendant of <p>` why wouldn't a span be more semantically correct? it could even take a prop of `block` for those who need it to behave like a block instead.

**Comment by CezaryDanielNowak** [comment]
https://github.com/CezaryDanielNowak/React-dotdotdot#sample-usage
p should be wrapped with div, not opposite.

**Comment by Kalita-Roman** [comment]
It would be great if there were a opportunity to choose tag which we wish to return. 
E.g. to use a prop. `tag`. We write
```
<Dotdotdot clamp={3} tag='span'>
    {someLongText}
</Dotdotdot>
```
and get a html
```
<span>
    Some long text...
</span>
```
instead of 
```
<div>
    Some long text...
</div>
```

**Comment by CezaryDanielNowak** [comment]
You can do following:
```
<Dotdotdot clamp={3}>
 <p>
    long text
    ...
 </p>
</Dotdotdot>
```

**Comment by Kalita-Roman** [comment]
As far as I got it, in this case we will have a redundant node 'div'. Like here 
```
<div>
    <p>
        long text
        ...
    </p>
</div>
```
