### ISSUE TITLE
ellipsis option not working

### ISSUE THREAD

**Issue by stanleycyang** [CezaryDanielNowak/React-dotdotdot#17]
<img width="171" alt="screen shot 2017-04-24 at 11 22 00 pm" src="https://cloud.githubusercontent.com/assets/3037893/25371294/dc4bdd6c-2944-11e7-8f21-b6be27d0c5d5.png">

I tried changing it to 'hello' and it did not work. Any idea why?

**Comment by williammustaffa** [comment]
Same here

**Comment by kkwiatkowski** [comment]
@stanleycyang @williammustaffa the prop for changing truncat character is: `truncationChar`, so in your case it should be (assuming that `Truncate` is `React-dotdotdot` component):
```javascript
<Truncate
  truncationChar={ 'hello' }
  clamp={ 7 }>
  <p>
    { testimonial }
  </p>
</Truncate>
```

Obviously there is misleading and not up-to-date information in README.
