### ISSUE TITLE
Use prop-types package instead React.PropTypes

### ISSUE THREAD

**Issue by untone** [CezaryDanielNowak/React-dotdotdot#18]
React 15.5 brings a new package called prop-types: https://facebook.github.io/react/blog/#migrating-from-react.proptypes. 

Please update definitions.

**Comment by dalkir** [comment]
Any updates?

**Comment by kkwiatkowski** [comment]
#19 merged, waiting for @CezaryDanielNowak to update npm registry.

**Comment by CezaryDanielNowak** [comment]
Published.
