### ISSUE TITLE
npm file is not the theme with master

### ISSUE THREAD

**Issue by yangxuanxing** [CezaryDanielNowak/React-dotdotdot#33]
![image](https://user-images.githubusercontent.com/3397523/35866068-27a2e18c-0b91-11e8-862a-68c8baf61e62.png)

in clamp.js line 276, npm file has ``sty.wordBreak = 'break-all';`` but the master doesnot;

the master should be right, and in fact i didnot want this style

**Comment by CezaryDanielNowak** [comment]
It was not released. 1.2.2 has it.
