### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by hubertguillemain** [CezaryDanielNowak/React-dotdotdot#40]
Would the maintainer(s) of thid repo be open to creating and maintaining the type definitions for seamless integration in typescript?

**Comment by CezaryDanielNowak** [comment]
Feel free to fork and create TS interface for this

**Comment by JoshuaKGoldberg** [comment]
FWIW, I've found it not to be worth the effort to keep a repo's typings updated - putting them on DefinitelyTyped tends to be more seamless.

**Comment by feimosi** [comment]
If anyone needs, here are the typings for v1.2.3

```ts
declare module 'react-dotdotdot' {
  import * as React from 'react';

  export interface DotdotdotProps {
    children?: React.ReactNode,
    clamp: string | number | boolean,
    truncationChar?: string,
    useNativeClamp?: boolean,
    className?: string,
    tagName?: string,
  }

  export default class Dotdotdot extends React.Component<DotdotdotProps> { }
}
```

**Comment by CezaryDanielNowak** [comment]
It's a part of 1.2.4
