### ISSUE TITLE
Take in clamp as an npm module?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [CezaryDanielNowak/React-dotdotdot#43]
You have `clamp.js` in your source repo. It'd be helpful for users of bundle loaders such as Rollup and Webpack if you referenced an npm module instead. That way our bundle loaders can intelligently deduplicate packages such as clamp.

**Comment by JoanClaret** [comment]
+1

**Comment by CezaryDanielNowak** [comment]
Original `josephschmitt/Clamp.js` is unmantained for a long time (6 years already). It's also buggy. Version included to React-dotdotdot has lots modifications.
I agree, that it would be better to host it as a Clamp.js fork but this way it's easier to maintain for me.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues in repos that haven't had updates in a few years. Cheers!
