### ISSUE TITLE
When page load, the full description flashes before getting resized

### ISSUE THREAD

**Issue by bolonio** [CezaryDanielNowak/React-dotdotdot#48]
We are using NextJs in our React application for **SSR (Server Side Rendering)**. When the page loads initially, it flashes the full description, causing the page to jump a bit (even leaving the text on top of some other elements). Is there any solution for SSR? Thanks :)

**Comment by andreyvital** [comment]
@bolonio—well I believe that the unique solution is to manually use `line-clamp` (which doesn't rely on browser measurements through JS): https://css-tricks.com/almanac/properties/l/line-clamp

Ofc, it won't work for all browsers, but I believe there's nothing we could really do about it. I guess the whole point is that most of browsers that are in recent versions won't see the text flashing, which is normally the majority of users.

**Comment by CezaryDanielNowak** [comment]
SSR doesn't know anything about an browser environment - resolution, font used, font-size, page zoom etc.  It's possible to make jump less visible but not possible to eliminate that.
