### ISSUE TITLE
Doesn't clamp the text. Inserts only dots at the end of the text

### ISSUE THREAD

**Issue by vamshikrishna144** [CezaryDanielNowak/React-dotdotdot#5]
```
import Dotdotdot from 'react-dotdotdot';
           <Dotdotdot clamp={3}>
                <a href="/notification" key={index}>
                  <span className="alert-heading">{notificationItem.subject}</span>
                  <span className="alert-content"> - {notificationItem.messageBody}</span>
                </a>
              </Dotdotdot>

```

![tooltip](https://cloud.githubusercontent.com/assets/1976095/17493987/a429508a-5d80-11e6-8919-971931581396.PNG)

**Comment by CezaryDanielNowak** [comment]
try add `display: block` or `display: inline-block` to a element

**Comment by vamshikrishna144** [comment]
That did not help.

**Comment by CezaryDanielNowak** [comment]
Hmm so Dotdotdot should be applied on `.alert-content`

**Comment by CezaryDanielNowak** [comment]
It will also work when `.alert-content` is removed

**Comment by vamshikrishna144** [comment]
The reason for the content to be split into alert-heading and alert-content is because alert content should be on the same line as heading and they have different styles. So the entire div(i.e heading and content) should be three lines of description. I applied Dotdotdot only to the content and this is what I have. 
![newnotification](https://cloud.githubusercontent.com/assets/1976095/17563723/a4324436-5efe-11e6-8263-013f148f9da6.PNG)

**Comment by CezaryDanielNowak** [comment]
That's why this one should work:

```
import Dotdotdot from 'react-dotdotdot';
<Dotdotdot clamp={3}>
    <a href="/notification" key={index}>
        <span className="alert-heading">{notificationItem.subject}</span> 
        - {notificationItem.messageBody}
    </a>
</Dotdotdot>
```

**Comment by vamshikrishna144** [comment]
Same thing Daniel. 
![third](https://cloud.githubusercontent.com/assets/1976095/17569189/181fa31e-5f15-11e6-9552-381c1bce96c5.PNG)

**Comment by vamshikrishna144** [comment]
Never mind. I gave a fixed height to the inner div and gave padding to the out div. 

Thanks for your time

**Comment by meijavier** [comment]
Hi @vamshikrishna144 can you share a snippet of your solution with this issue? I'm also experiencing this. The clamp should be 2 lines but it only clamps to 1 and ends it with an ellipsis. Thanks for your reply.

**Comment by CezaryDanielNowak** [comment]
@meijavier are you using latest react-dotdotdot version?

**Comment by meijavier** [comment]
@CezaryDanielNowak yes. Version 1.3.1

**Comment by meijavier** [comment]
Here's what it looks like:

![image](https://user-images.githubusercontent.com/19919659/62506322-c9801200-b832-11e9-9432-a5d1f94ba439.png)

The title, subtitle and subtext are this long: 
![image](https://user-images.githubusercontent.com/19919659/62506380-f7655680-b832-11e9-801f-38b2949e38ff.png)

So it should be clamp 2 lines but it only clamps 1.

**Comment by meijavier** [comment]
Here's what it looks like:

iPhone X
![image](https://user-images.githubusercontent.com/19919659/62506322-c9801200-b832-11e9-9432-a5d1f94ba439.png)

Nexus 7
![image](https://user-images.githubusercontent.com/19919659/62506524-8c684f80-b833-11e9-836e-cc3e0a176888.png)

The title, subtitle and subtext are this long: 
![image](https://user-images.githubusercontent.com/19919659/62506380-f7655680-b832-11e9-801f-38b2949e38ff.png)

So it should clamp 2 lines but it only clamps 1.

I tested this using the latest Chrome browser, this happens to all standard smartphone viewports (iphones, Note 3, Nexus 7, etc)

**Comment by meijavier** [comment]
@CezaryDanielNowak or does this to have to do with what is listed in the "Known Issues"?

> react-dotdotdot does not work with text containers with nested markup.

**Comment by CezaryDanielNowak** [comment]
@meijavier Might be, unfortunetely I'm not maintaining any project with react-dotdotdot anymore, so I am not familiar with all possible cases :<
