### ISSUE TITLE
Dotdotdot for IE

### ISSUE THREAD

**Issue by vamshikrishna144** [CezaryDanielNowak/React-dotdotdot#6]
Hi there, 
I have the following code:

<div className="notification">
              <Dotdotdot className="notification-dot" clamp={3}>
                  <a href="/notification" key={index}>
                      <span className="alert-heading">{notificationItem.subject}</span>
                      <span className="alert-content">- {notificationItem.messageBody}</span>
                  </a>
              </Dotdotdot>
            </div>

It does work for Chrome but it does not work on IE.
I see the following on IE:
![image](https://cloud.githubusercontent.com/assets/1976095/17820389/a90f5c00-661a-11e6-856d-f4d3206a214d.png)

The div renders but has no value. Here is the screenshot for IE element console:
![image](https://cloud.githubusercontent.com/assets/1976095/17820441/dae7dd4c-661a-11e6-943f-81974658e2ed.png)

**Comment by vamshikrishna144** [comment]
The console on IE says "Unknown props `first`, `last`, `ellipsis`, `boundaryLinks`, `items`, `maxButtons`, `activePage`, `prev`, `next`, `buttonComponentClass` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop "

**Comment by famu1hundred** [comment]
+1, this library doesn't seem to work in IE11

**Comment by kkwiatkowski** [comment]
This issue is fixed by #11 and should be closed.
