### ISSUE TITLE
clamp: auto in parent elements with many childs

### ISSUE THREAD

**Issue by rurquia** [CezaryDanielNowak/React-dotdotdot#8]
When the vertical ellipse is placed in an element with a parent with many childs the 'auto' clamp dont works. Its unable to calculate the correct height. 

If you replace the line 92 of clamp.js (in the function getMaxLines) with this other one it ill do it well
var availHeight = height || (element.parentNode.clientHeight-element.offsetTop),

**Comment by CezaryDanielNowak** [comment]
I hope it works now :)
